#!/usr/bin/env bash

# Function to clamp a value between a minumum and maximum
clamp {
	local min=$1
	local max=$2
	local val=$3
	python -c "print(max($min, min($val, $max)))"
}

direction=$1
current=$2

if [ "$direction" = "down" ]; then
	target=$(clamp 1 10 $(($current+1)))
	echo "Jumping to workspace $target"
	hyprctl dispatch workspace "$target"
elif [ "$direction" = "up" ]; then
	target=$(clamp 1 10 $(($current-1)))
	echo "Jumping to workspace $target"
	hyprctl dispatch workspace "$target"
else
  echo "Usage: $0 {up|down} current_workspace"
  exit 1
fi
