[bar]
scale = 0.75

[[bar.layout]]
monitor = "*"
left = ["dashboard", "window-title"]
center = ["weather", "custom-aqi", "clock", "idle-inhibit", "notifications"]
right = ["brightness", "volume", "network", "battery"]

[styling.palette]
# Dracula pallete
bg = "#191a21"       # bg-base
surface = "#282a36"  # bg-surface
elevated = "#44475a" # bg-surface-elevated
fg = "#f8f8f2"       # fg-default
fg_muted = "#6272a4" # fg-muted
primary = "#bd93f9"  # accent
red = "#ff5555"      # red status-error
yellow = "#f1fa8c"   # yellow status-warning
green = "#50fa7b"    # green
blue = "#8be9fd"     # blue

[general]
font-mono = "Mononoki Nerd Font Mono"

[osd]
enabled = false

[modules.battery]
format = "{{ percent }}"
icon-bg-color = "blue"
label-color = "blue"
thresholds = [
  { above = 80, label-color = "green" },
  { below = 30, icon-bg-color = "status-warning" },
  { below = 15, icon-bg-color = "status-error", label-color = "status-error"}
]

[modules.brightness]
format = "{{ percent }}"
right-click = "$HOME/.local/bin/ABToggle.sh"

[modules.clock]
format = "%H:%M %a, %b %d"
icon-bg-color = "yellow"
label-color = "fg-default"

[modules.dashboard]
icon-bg-color = "red"

[modules.idle-inhibit]
label-show = false
icon-bg-color = "red"

[modules.network]
icon-bg-color = "green"
label-color = "green"
right-click = "nm-connection-editor"

[modules.notifications]
icon-bg-color = "bg-surface-elevated"
label-show = false
thresholds = [
 { above = 1, icon-bg-color = "green" }
]

[modules.volume]
format = "{{ percent }}"
icon-bg-color = "accent"
label-color = "accent"

[modules.weather]
units = "imperial"
icon-bg-color = "yellow"
label-color = "yellow"

[modules.window-title]
icon-bg-color = "green"
label-color = "green"

[[modules.custom]]
id = "aqi"
command = "~/.config/wayle/scripts/waqi.py"
interval-ms = 300000
format = "{{ text }}"
hide-if-empty = true
left-click = "xdg-open https://aqicn.org"
icon-map = {
# wayle icons install lucide thumbs-up thumbs-down triangle-alert octagon-alert biohazard
  "good" = "ld-thumbs-up",
  "moderate" = "ld-info",
  "sensitive"  = "ld-thumbs-down",
  "unhealthy" = "ld-triangle-alert",
  "veryunhealthy" = "ld-octagon-alert",
  "hazardous" = "ld-biohazard"
}
