[bar]
scale = 0.75

[[bar.layout]]
monitor = "*"
left = ["dashboard", "window-title"]
center = ["weather", "custom-aqi", "clock", "idle-inhibit", "notifications"]
right = ["brightness", "volume", "network", "battery"]

[styling.palette]
# Dracula pallete
# All color options https://wayle.app/config/types#color-value
# Colors             # Variables
bg = "#191a21"       # bg-base
surface = "#282a36"  # bg-surface
elevated = "#44475a" # bg-surface-elevated
fg = "#f8f8f2"       # fg-default
fg_muted = "#6272a4" # fg-muted
primary = "#bd93f9"  # accent
red = "#ff5555"      # red status-error
yellow = "#f1fa8c"   # yellow status-warning
green = "#50fa7b"    # green
blue = "#8be9fd"     # blue

[general]
font-sans = "Arimo Nerd Font"
font-mono = "Mononoki Nerd Font Mono"

[osd]
enabled = false
# With auto brightness this might get annoying
position = "top-right"
margin = 0

[wallpaper]
engine-enabled = true
transition-type = "random"
transition-duration = 3
cycling-enabled = true
cycling-directory = "/home/marty/Pictures/wallpapers"
cycling-mode = "shuffle"
cycling-interval-mins = 30

[modules.battery]
format = "{{ percent }}"
icon-bg-color = "blue"
label-color = "fg-default"
thresholds = [
  { above = 90, label-color = "green" },
  { below = 30, icon-bg-color = "status-warning" },
  { below = 15, icon-bg-color = "status-error", label-color = "status-error"}
]

[modules.brightness]
format = "{{ percent }}"
label-color = "fg-default"
right-click = "$HOME/.local/bin/ABToggle.sh"

[modules.clock]
format = "%I:%M %p"
icon-bg-color = "fg-default"
label-color = "fg-default"

[modules.dashboard]
icon-bg-color = "accent"

[modules.idle-inhibit]
label-show = false
icon-bg-color = "accent"

[modules.network]
icon-bg-color = "green"
label-color = "fg-default"
right-click = "nm-connection-editor"

[modules.notifications]
icon-bg-color = "bg-surface-elevated"
label-show = false
thresholds = [
 { above = 1, icon-bg-color = "green" }
]

[modules.volume]
format = "{{ percent }}"
icon-bg-color = "accent"
label-color = "fg-default"

[modules.weather]
units = "imperial"
icon-bg-color = "fg-default"
label-color = "fg-default"

[modules.window-title]
icon-bg-color = "bg-surface-elevated"
icon-color = "fg-muted"
label-color = "fg-default"

[[modules.custom]]
id = "aqi"
command = "~/.config/wayle/scripts/waqi.py"
interval-ms = 300000
format = "{{ text }}"
icon-bg-color = "fg-default"
label-color = "fg-default"
hide-if-empty = true
left-click = "xdg-open https://aqicn.org"
icon-map = {
# wayle icons install lucide thumbs-up thumbs-down triangle-alert octagon-alert biohazard
  "Unknown" = "ld-x",
  "Good" = "ld-thumbs-up",
  "Moderate" = "ld-info",
  "Sensitive"  = "ld-thumbs-down",
  "Unhealthy" = "ld-triangle-alert",
  "Very_Unhealthy" = "ld-octagon-alert",
  "Hazardous" = "ld-biohazard"
}
