# FONTS - list all with `kitty +list-fonts` command
font_family Hack Nerd Font Mono
font_size 12

# CURSOR CUSTOMIZATION
cursor_shape block
cursor_stop_blinking_after 0

# SCROLLBACK
scrollback_lines 5000

# MOUSE
underline_hyperlinks always
strip_trailing_spaces smart
focus_follows_mouse yes

# TERMINAL BELL
enable_audio_bell no

# WINDOW LAYOUT
enabled_layouts horizontal, vertical

# TAB BAR
tab_bar_edge top
tab_bar_style powerline
tab_title_max_length 25

# COLOR SCHEME
# Catppuccin-Mocha
include current-theme.conf

# ADVANCED
update_check_interval 0

# KEYBOARD SHORTCUTS
kitty_mod ctrl+shift

# Window management
map kitty_mod+t new_window
map kitty_mod+w close_window
map ctrl+alt+tab next_window
map kitty_mod+alt+tab previous_window

# Tab management
map ctrl+tab next_tab
map kitty_mod+tab previous_tab
map ctrl+t new_tab
map ctrl+w close_tab
map ctrl+. move_tab_forward
map ctrl+, move_tab_backward

# Layout management
map kitty_mod+l next_layout

# Font sizes
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# Clipboard
map kitty_mod+v paste_from_selection

# Scrolling
map kitty_mod+up scroll_line_up
map kitty_mod+k scroll_line_up
map kitty_mod+down scroll_line_down
map kitty_mod+j scroll_line_down
map kitty_mod+page_up scroll_page_up
map kitty_mod+page_down scroll_page_down
map kitty_mod+home scroll_home
map kitty_mod+end scroll_end

# Miscellaneous
map kitty_mod+u kitten unicode_input
map kitty_mod+r load_config_file
map ctrl+u send_text all \x15
map ctrl+c copy_and_clear_or_interrupt
