[main]
# include=<not set>
namespace=launcher
font=Hack Nerd Font Mono
placeholder=Search
# prompt=>
icon-theme=Dracula
icons-enabled=yes
anchor=center
width=50
tabs=2
horizontal-pad=20
layer=overlay

[colors]
background=282a36ff
text=f8f8f2ff
prompt=f8f8f2ff
placeholder=6272a4ff
input=f8f8f2ff
match=8be9fdff
selection=44475add
selection-text=f8f8f2ff
selection-match=8be9fdff
border=bd93f9ff

[border]
width=1
radius=12
