# https://malpenzibo.github.io/ashell/
log_level = "warn"

position = "Top"  # "Top" or "Bottom"
layer = "Top"  # "Bottom", "Top", or "Overlay"
enable_esc_key = true  # Pressing Escape closes open menus

[modules]
left = ["Aqi", "Tempo"]
center = ["WindowTitle"]
right = [["Tray", "Updates", "Notifications"], ["Settings", "Privacy"]]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'kitty -e bash -c "paru; echo Done - Press enter to exit; read" &'
interval = 3600

[[CustomModule]]
name = "Aqi"
type = "Button"
icon = "󰵄"
command = "xdg-open https://aqicn.org/here"
listen_cmd = "~/.config/ashell/scripts/aqi.py"
icons."good" = "󰡳"
icons."moderate" = "󰡵"
icons."sensitive" = "󰊚"
icons."unhealthy" = "󰡴"
icons."very_unhealthy" = ""
icons."hazardous" = ""
alert = "sensitive|unhealthy|hazardous"

[window_title]
mode = "Title"
truncate_title_after_length = 75

[tray]
right_click = "menu"

[tempo]
clock_format = "%I:%M %p"
weather_location = "Current"
weather_indicator = "IconAndTemperature"  # "Icon", or "None"
wind_speed_unit = "Mph"  # "Kmh", "Mph", or "Ms"

[notifications]
format = "%H:%M"
show_timestamps = true
show_bodies = true
grouped = true
toast_position = "top_left"

[settings]
lock_cmd = "loginctl lock-session &"

suspend_cmd = "systemctl suspend-then-hibernate"
hibernate_cmd = "systemctl hibernate"

wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
battery_format = "IconAndPercentage"

indicators = [
  "IdleInhibitor",
  "Network",
  "Vpn",
  "Bluetooth",
  "Audio",
  "Battery"
]

[osd]
enabled = true
timeout = 1500  # milliseconds
show_volume_percentage = true
show_brightness_percentage = true

[animations]
enabled = true

[appearance]
style = "Solid"  # "Islands", "Solid", or "Gradient"
font_name = "Mononoki Nerd Font Mono"
# scale_factor = 1.1

success_color = "#50FA7B"
warning_color = "#FFB86C"
danger_color = "#FF5555"
text_color = "#F8F8F2"

[appearance.primary_color]
base = "#BD93F9"  # Main accent color
text = "#282A36"

[appearance.background_color]
base = "#21222C"
weak = "#44475A"
strong = "#282A36"
text = "#F8F8F2"
